# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-26 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chhotufy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='code',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
