# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-26 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chhotufy', '0003_auto_20180526_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='code',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
